*realizacoes{
1
}
*Kozeny-Carman{
0
3.60e-12 1.0
}
*permeabilidade{
1
./fields/perm_amostra_
./fields/perm_amostra_
7.5e-14 0.8
}
*porosidade{
1
./fields/phi_amostra_
0.0 1.0
1
}
*beta{
0
./fields/e200x20_10_
1.0e-12    1.0
}
*modulo_de_young_reservatorio{
1
./fields/young_amostra_
8.6e+08 0.6
}
*modulo_de_young_dominio_meio{
0
./fields/youngR_amostra_
9.531568D+07 0.315735
-800 -720
}
*modulo_de_young_dominio_top{
0
./fields/youngT_amostra_
5.2E+08   0.2
-800 -240
}
*mixing{
0
./mix/mix_twohetK_
0
}
*producao{
0
./prod/caps540_NEW_2way_Rreal_
250
}