*solver_hidrodinamica{
skyline
}
*solver_geomecanica{
skyline
}
*top_external_load_em_pascal{
0.0E+0
}
*sea_depth_in_meters{
0.0E+0
}
*instante_inicial{
0.0
}
*tempo_total_de_simulacao{
30.0
}
*numero_de_calculos_da_velocidade{
3
}
*tempo_de_inicio_de_injecao{
0.0D0
}
*pressao_de_referencia{
0.0D7
}
*cota_de_referencia{
0.0D0
}
*pressao_no_fundo_do_poco_de_producao{
0.0E0
}
*cota_do_fundo_do_poco{
0.0
}
*tempo_para_a_descompressao_do_poco{
5.0e5
}
*coordenadas_poco{
4
1.1950000e+03 -7.9500000e+02 0.0000000e+00
1.1950000e+03 -7.7500000e+02 0.0000000e+00
1.1950000e+03 -7.5500000e+02 0.0000000e+00
1.1950000e+03 -7.3500000e+02 0.0000000e+00
}
